services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/datashark/csv:/app/csv
      - ~/datashark/archive:/app/archive
    ports:
      - "9292:9292"
    env_file:
      - .env.development

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /home/sftpuser/upload:/app/csv
      - /home/sftpuser/archive:/app/archive
    ports:
      - "9292:9292"
    env_file:
      - .env.production

volumes:
  production_csv:
  production_archive: